### 3. 중복 데이터
* 중복 데이터가 존재하면 분석 결과를 왜곡하게 된다.
* 중복 데이터 처리 함수
    - df.duplicated() : 중복된 행(가로)이 있을 경우 True
    - df.drop_duplicates() : 중복되는 행(가로)을 제거
---

In [1]:
import pandas as pd

df = pd.read_csv("../../data_set/2.데이터 클린징/test1.csv")
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2
5  a   1   1

In [2]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
5     True
dtype: bool

In [3]:
df.duplicated().sum()

np.int64(2)

In [4]:
df.drop_duplicates(inplace=True)
df

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.reset_index(drop=True)

  c1  c2  c3
0  a   1   1
1  b   1   2
2  a   2   2
3  b   2   2