### 회귀
* 독립변수가 종속변수에 영향을 미치는지 알아보고자 할 때 사용
* 연속형 변수들에 대해 두 변수 사이의 적합도를 측정
* 단순회귀
    - 하나의 종속변수와 하나의 독립변수 사이의 관계 분석
* 다중회귀
    - 하나의 종속변수와 여러 독립변수 사이의 관계 분석

### 회귀 평가지표
* MSE(Mean Squared Error)(평균 제곱 오차)
    - 예측값과 실제값의 차이에 대한 제곱(잔차 제곱)에 대하여 평균을 낸 값
    - 회귀 문제에서 가장 많이 사용하는 성능 지표
    - 모델을 평가하는 평가 지표로 오차를 나타내는 식이므로 수치가 적을 수록 좋은 모델
    - 다른 모델과 비교해야만 성능이 좋은지 알 수 있다.
* RMSE(Root Mean Squared Error)
    - 0에 가까울수록 좋은 모델
    - MSE에 ROOT를 쒸운 값. 즉 MSE의 제곱을 다시 원래 값으로 가져옴(가독성 높임)
* MSE & RMSE
    * 오차에 제곱을 진행했기 때문에 오차가 큰 값은 더 크게 벌어지게 된다. 그럼 결국 좋지 않은 모델로 평가 될수 있다. 즉, 큰오차가 있는지 없는지 판단할 때 사용할 수 있다
* MAE(Mean Absolute Error, 평균 절대 오차)
    - 단순 평균 오차를 보기 때문에 위의 경우와 다르게 오차가 크더라도 전체적으로 안정적인 오차 평균을 구할 수 있다
    - 실제값 대비 예측값의 오차를 나타내는 것으로 값이 낮을 수록 좋다
    - 예측값과 실제값의 차이에 대한 절대값에 대하여 평균을 낸 값
* MAPE(Mean Absolute Percentage Error, 평균 절대 비율 오차)
    - 실제값 대비 예측차이가 얼마나 있는지를 비율(%)로 측정
    - 퍼센트값을 가지며 0에 가까울수록 회귀모형의 성능이 좋다고 해석
* r2(결정계수)
    - 0~1 사이의 값을 표현해 주며 r2의 값이 높을수록 좋다
    - 예측 모델과 실제 모델이 얼마나 강한 상관관계를 가지고 있는지
    - 즉, 데이터 변화에 대해 얼마나 잘 설명되는지를 표현하는 것
    - 예) 실제 데이터 : 1,2,3 -> 예측 데이터 0.8, 1.7, 2.7 -> 실 데이터 흐름과 비슷하게 예측하는 기준(설명이 잘 됨)

* 타겟 데이터
    - 1978년 보스턴 주택 가격
    - 506개 타운의 주택 가격 중앙값(단위 1,000달러)
* 특징 데이터
    - CRIM : 범죄율
    - ZM : 25,000평방 피트 당 주거용 토지의 비율
    - INDUS : 비소매상업지역 면적 비율
    - CHAS : 찰스강의 경계에 위치한 경우는 1, 아니면 0(통로가 하천을 향하면1, 아니면 0)
    - NOX : 일산화질소 농도(천만분의 1)
    - RM : 주택당 방수
    - AGE : 1940년 이전에 건축된 주택의 비율
    - DIS : 5개 주요 고용센터까지의 가중거리
    - RAD : 고속도로 접근성 지수
    - TAX : 재산세율
    - PTRATIO : 학생/교사 비율
    - B ; 인구 중 흑인 거주 비율
    - LSTAT : 인구 중 하위 계층 비율
    - MEDV : 본인 소유의 주택가격(중앙값) (단위: $1,000)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data_set/6.회귀/HousingData.csv')
df.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14,21.6

In [5]:
y = df['MEDV']
X = df.drop( ['MEDV'], axis=1 )
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
X_train.shape, X_test.shape

((354, 13), (152, 13))

In [9]:
from sklearn.neighbors import KNeighborsRegressor

In [10]:
kn = KNeighborsRegressor()
kn.fit(X_train, y_train)

KNeighborsRegressor()

In [13]:
kn.score(X_train, y_train), kn.score(X_test, y_test) # r2 결정 계수(흐름 잘 파악했나)

(0.6529415468877569, 0.2999825235056466)

In [14]:
pred = kn.predict(X_test)

In [15]:
pred

array([18.76, 21.92, 20.32, 11.64, 31.8 , 10.62, 19.38, 21.18, 33.6 ,
       25.9 , 23.8 , 25.84, 19.08, 10.96, 26.68, 28.44, 12.78, 23.32,
       24.74, 26.82, 23.5 , 22.96, 26.62, 30.5 , 27.34, 26.62, 23.54,
        9.14, 23.  , 33.86, 20.26, 21.36, 29.18, 30.5 , 26.66, 19.98,
       21.76, 20.32, 26.58, 12.46, 24.58, 20.42, 23.04, 24.78, 39.08,
       17.64, 19.26, 27.72, 19.3 , 29.1 , 22.02, 10.76, 24.98, 24.9 ,
       24.82, 25.84, 17.16, 32.14, 18.22, 22.08, 13.18, 33.86, 22.36,
       16.52, 21.18, 24.24, 13.06, 12.7 , 18.5 , 19.04, 12.78, 21.38,
       21.92, 11.66, 28.92, 16.06, 23.62, 21.86, 29.06, 18.22, 27.66,
       24.52, 20.32, 11.64, 16.16, 26.62, 25.34, 23.18, 27.6 , 36.18,
       15.2 , 19.52, 33.46, 30.76, 22.68, 12.78, 21.44, 23.02, 31.42,
       18.86, 27.76, 23.8 , 34.2 , 26.28, 22.04, 19.96, 11.42, 29.18,
       27.96, 23.16, 22.92,  9.44, 26.82, 23.32, 18.22, 38.48, 19.96,
       20.98, 28.1 , 15.36, 24.24, 27.66, 24.96, 17.14, 17.42, 26.66,
       22.92, 25.34, 17.1 , 23.2 , 33.18, 14.3 , 16.44, 34.16, 28.5 ,
       34.2 , 39.36, 25.2 , 25.34, 21.84, 24.48, 17.6 , 25.2 , 10.8 ,
       34.2 , 21.46, 26.3 , 19.3 , 26.4 , 32.44, 18.76, 25.14])

In [16]:
from sklearn.metrics import mean_squared_error, r2_score

In [18]:
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)

In [19]:
print('mse :', mse)
print('rmse :', rmse)
print('r2 :', r2)

mse : 55.914447368421044
rmse : 7.4775963630314415
r2 : 0.2999825235056466

In [20]:
from sklearn.ensemble import RandomForestRegressor

In [21]:
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)

RandomForestRegressor()

In [23]:
pred = rfr.predict(X_test)
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)

print('mse :', mse)
print('rmse :', rmse)
print('r2 :', r2) #0.7 ~ 0.9 값이 좋음

print('train :', rfr.score(X_train, y_train))
print('test :', rfr.score(X_test, y_test))

mse : 15.771663572368412
rmse : 3.9713553822805148
r2 : 0.8025476302877207
train : 0.975097399199466
test : 0.8025476302877207